### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Abdulmomen96** [liboyue/beer#1]
Hi, 
I've faced the following issue while running the experiment notebook

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-4d8e69f01caf> in <module>
     23 
     24 configs = BEER_configs + CHOCO_SGD_configs + len(baseline_exps) * [{}]
---> 25 exps = [BEER(p, n_iters=n_iters, batch_size=batch_size, x_0=x_0, W=W, **config) for config in BEER_configs] \
     26         + [CHOCO_SGD(p, n_iters=int(n_iters * 2), batch_size=batch_size, x_0=x_0, W=W, **config) for config in CHOCO_SGD_configs] \
     27         + baseline_exps

<ipython-input-25-4d8e69f01caf> in <listcomp>(.0)
     23 
     24 configs = BEER_configs + CHOCO_SGD_configs + len(baseline_exps) * [{}]
---> 25 exps = [BEER(p, n_iters=n_iters, batch_size=batch_size, x_0=x_0, W=W, **config) for config in BEER_configs] \
     26         + [CHOCO_SGD(p, n_iters=int(n_iters * 2), batch_size=batch_size, x_0=x_0, W=W, **config) for config in CHOCO_SGD_configs] \
     27         + baseline_exps

C:\ProgramData\Anaconda3\lib\site-packages\beer\optim\BEER.py in __init__(self, model, gamma, **kwargs)
      7 class BEER(CompressedOptimizer):
      8     def __init__(self, model, gamma=0.1, **kwargs):
----> 9         super().__init__(model, **kwargs)
     10         self.gamma = gamma
     11 

C:\ProgramData\Anaconda3\lib\site-packages\beer\optim\CompressedOptimizer.py in __init__(self, model, lr, G, world_size, rank, compression_type, compression_params, **kwargs)
      8 class CompressedOptimizer(Optimizer):
      9     def __init__(self, model, lr=1, G=None, world_size=1, rank=0, compression_type=None, compression_params=[], **kwargs):
---> 10         super().__init__(model.module.parameters(), dict())
     11         log.info(f'world size = {world_size}, rank = {rank}, lr = {lr}, compression = {compression_type}({compression_params})')
     12         self.lr = lr

AttributeError: 'LogisticRegression' object has no attribute 'module'

The LogisticRegression problem was implemented in NumPy, not with Torch tensors.

**Comment by liboyue** [comment]
Could you try again now? I added the file, it should work now.

**Comment by Abdulmomen96** [comment]
Thanks, the problem is solved!
